#!/usr/bin/env bash
# Render human-readable queue views from slices/queue.json.
#
# Primary output:
#   slices/slicemap.md
#
# Legacy compatibility shadow:
#   slices/queue.md
#
# The JSON is canonical. The markdown files are courtesy renderings for humans.
# Call this after any mutation to queue.json to keep the views in sync.
#
# Usage:
#   render_queue.sh [json_path] [slicemap_path] [legacy_queue_md_path]
#
# Defaults:
#   json_path             = slices/queue.json
#   slicemap_path         = slices/slicemap.md
#   legacy_queue_md_path  = slices/queue.md
#
# Exits 0 on success, 1 on failure (jq missing, JSON missing, parse error).

set -euo pipefail

JSON_PATH="${1:-slices/queue.json}"
SLICEMAP_PATH="${2:-slices/slicemap.md}"
LEGACY_PATH="${3:-slices/queue.md}"

resolve_jq() {
  if command -v jq >/dev/null 2>&1; then
    command -v jq
    return 0
  fi

  if command -v jq.exe >/dev/null 2>&1; then
    command -v jq.exe
    return 0
  fi

  return 1
}

JQ_BIN="$(resolve_jq)" || { echo "render_queue.sh: jq not found" >&2; exit 1; }
[[ -f "$JSON_PATH" ]] || { echo "render_queue.sh: $JSON_PATH not found" >&2; exit 1; }

mkdir -p "$(dirname "$SLICEMAP_PATH")"
mkdir -p "$(dirname "$LEGACY_PATH")"

"$JQ_BIN" -r '
  def agent_tag(a): a // "(unassigned)";
  def joined(a): if (a // []) | length == 0 then "(none)" else ((a // []) | join(", ")) end;
  def yesno(v): if v then "Yes" else "No" end;
  def layer_name(n):
    if n == 1 then "Foundation"
    elif n == 2 then "Data"
    elif n == 3 then "Security"
    elif n == 4 then "Logic"
    elif n == 5 then "Interface"
    elif n == 6 then "Features & Release"
    else "Layer " + (n | tostring)
    end;

  . as $root
  | ((.slices // []) | sort_by(.layer, .id)) as $slices
  | ($slices | length) as $total
  | ($slices | group_by(.status) | map({key:.[0].status, value:length}) | from_entries) as $by_status
  | ($slices | group_by(.layer)  | map({key:(.[0].layer|tostring), value:length}) | from_entries) as $by_layer
  | "# Slice Map",
    "",
    "_Generated: \(.generated_at // "unknown") · Generated by: \(.generated_by // "unknown") · Pipeline mode: \(.pipeline_mode // "full") · Schema version: \(.version // 1)_",
    "",
    "> This file is a rendering of `slices/queue.json`. The JSON is canonical; this markdown regenerates after every queue mutation.",
    "",
    "## Summary",
    "",
    "- **Total:** \($total)",
    "- **By status:** pending: \(($by_status.pending // 0)) · in_progress: \(($by_status.in_progress // 0)) · completed: \(($by_status.completed // 0)) · blocked_retry: \(($by_status.blocked_retry // 0)) · refused: \(($by_status.refused // 0)) · escalated: \(($by_status.escalated // 0))",
    "- **By layer:** " + ([range(1;7) | "L\(.): \(($by_layer[(.|tostring)]) // 0)"] | join(" · ")),
    "",
    (if (($root.planning_advisories // []) | length) > 0 then
      "## Planning Advisories",
      "",
      ($root.planning_advisories[] |
        "### \(.id // "(unlabeled advisory)")",
        "",
        "- **Severity:** \(.severity // "medium")",
        "- **Summary:** \(.summary // "—")",
        "- **Decision:** \(.decision // "—")",
        "- **User response required:** \(yesno(.user_response_required // false))",
        "- **References:** \(joined(.references))",
        "- **Affects slices:** \(joined(.affects_slices))",
        ""
      )
    else
      empty
    end),
    (range(1;7) as $layer
      | ($slices | map(select(.layer == $layer))) as $layer_slices
      | select(($layer_slices | length) > 0)
      | "## Layer \($layer) — \(layer_name($layer))",
        "",
        ($layer_slices[] |
          "### [Slice ID: \(.id)]" + (if .phase then " [Phase: \(.phase)]" else "" end) + " — \(.title // "(untitled)")",
          "",
          "- **Status:** `\(.status // "pending")`",
          "- **Assigned Agent:** \(agent_tag(.author_agent))",
          "- **Objective:** \(.objective // "—")",
          "- **Bounded Context:** \(.bounded_context // "?")",
          "- **Depends On:** \(joined(.depends_on))",
          "- **Write Set:** \(joined(.write_set))",
          "- **Target LOC:** \(.target_loc // "?")",
          "- **Context to Update:** `\(.context_to_update // "project_state.md")`",
          "- **Review Required:** \(yesno(.review_required // false))",
          "- **Attempts:** \(.attempts // 0) · **Micro-corrections:** \(.micro_corrections_used // 0)",
          "- **Traces to:**",
          "  - PRD: \(joined(.traces_to.prd))",
          "  - ADR: \(joined(.traces_to.adr))",
          "  - DDD: \(joined(.traces_to.ddd))",
          "  - ISC: \(joined(.traces_to.isc))",
          "  - DSD: \(joined(.traces_to.dsd))",
          "- **Implementation Details:**",
          ((.implementation_details // []) | .[] | "  - \(.)"),
          "- **Verification Steps:**",
          "  - Acceptance: `\(.verification_steps.acceptance // "—")`",
          "  - ISC detection: `\(.verification_steps.isc_detection // "—")`",
          "  - DSD conformance: `\(.verification_steps.dsd_conformance // "—")`",
          "- **Human Check Needed?:** " +
            (if (.human_check_needed.required // false) then
              "Yes — \((.human_check_needed.reason // "") | if length == 0 then "reason not provided" else . end)" +
              (if .human_check_needed.resolved_at then " — resolved at \(.human_check_needed.resolved_at)" else " — unresolved" end)
            else
              "No"
            end),
          "- **Verdicts:** karai=\(((.verdicts.karai_structural) // "—")) · bishop=\(((.verdicts.bishop) // "—")) · tiger_claw=\(((.verdicts.tiger_claw) // "—"))",
          (if .completed_at then "- **Completed:** \(.completed_at)" else empty end),
          (if .escalation_reason then "- **Escalation:** \(.escalation_reason)" else empty end),
          ""
        )
    )
' "$JSON_PATH" > "$SLICEMAP_PATH" 2>/dev/null || {
  echo "render_queue.sh: failed to render $SLICEMAP_PATH" >&2
  exit 1
}

if [[ "$LEGACY_PATH" != "$SLICEMAP_PATH" ]]; then
  cat "$SLICEMAP_PATH" > "$LEGACY_PATH" || {
    echo "render_queue.sh: failed to write $LEGACY_PATH" >&2
    exit 1
  }
fi

exit 0
