#!/usr/bin/env bash
# Render slices/queue.md from slices/queue.json.
#
# The JSON is canonical. The markdown is a courtesy for humans.
# Call this after any mutation to queue.json to keep the two in sync.
#
# Usage:
#   render_queue.sh [json_path] [md_path]
# Defaults:
#   json_path = slices/queue.json
#   md_path   = slices/queue.md
#
# Exits 0 on success, 1 on failure (jq missing, JSON missing, parse error).

set -uo pipefail

JSON_PATH="${1:-slices/queue.json}"
MD_PATH="${2:-slices/queue.md}"

command -v jq >/dev/null 2>&1 || { echo "render_queue.sh: jq not found" >&2; exit 1; }
[[ -f "$JSON_PATH" ]] || { echo "render_queue.sh: $JSON_PATH not found" >&2; exit 1; }

jq -r '
  def agent_tag(a): a // "(unassigned)";
  def joined(a): if (a // []) | length == 0 then "(none)" else ((a // []) | join(", ")) end;

  . as $root
  | (.slices // []) as $slices
  | ($slices | length) as $total
  | ($slices | group_by(.status) | map({key:.[0].status, value:length}) | from_entries) as $by_status
  | ($slices | group_by(.layer)  | map({key:(.[0].layer|tostring), value:length}) | from_entries) as $by_layer
  | "# Slice Queue",
    "",
    "_Generated: \(.generated_at // "unknown") · Generated by: \(.generated_by // "unknown") · Pipeline mode: \(.pipeline_mode // "full") · Schema version: \(.version // 1)_",
    "",
    "> This file is a rendering of `slices/queue.json`. The JSON is canonical; this markdown regenerates after every status change.",
    "",
    "## Summary",
    "",
    "- **Total:** \($total)",
    "- **By status:** pending: \(($by_status.pending // 0)) · in_progress: \(($by_status.in_progress // 0)) · completed: \(($by_status.completed // 0)) · blocked_retry: \(($by_status.blocked_retry // 0)) · refused: \(($by_status.refused // 0)) · escalated: \(($by_status.escalated // 0))",
    "- **By layer:** " + ([range(1;7) | "L\(.): \(($by_layer[(.|tostring)]) // 0)"] | join(" · ")),
    "",
    "## Slices",
    "",
    ($slices[] |
      "### \(.id) — \(.title // "(untitled)")",
      "",
      "- **Status:** `\(.status // "pending")`  ·  **Agent:** \(agent_tag(.author_agent))  ·  **Layer:** L\(.layer // "?")  ·  **Context:** \(.bounded_context // "?")  ·  **Target LOC:** \(.target_loc // "?")",
      "- **Attempts:** \(.attempts // 0)  ·  **Review required:** \(.review_required // false)  ·  **Human check:** \((.human_check_needed.required // false) | tostring)",
      "- **Verdicts:** karai=\(((.verdicts.karai_structural) // "—")) · bishop=\(((.verdicts.bishop) // "—")) · tiger_claw=\(((.verdicts.tiger_claw) // "—"))",
      (if .completed_at then "- **Completed:** \(.completed_at)" else empty end),
      (if .escalation_reason then "- **Escalation:** \(.escalation_reason)" else empty end),
      "- **Objective:** \(.objective // "—")",
      "- **Context to update:** `\(.context_to_update // "project_state.md")`",
      "- **Traces to:**",
      "  - PRD: \(joined(.traces_to.prd))",
      "  - ADR: \(joined(.traces_to.adr))",
      "  - DDD: \(joined(.traces_to.ddd))",
      "  - ISC: \(joined(.traces_to.isc))",
      "  - DSD: \(joined(.traces_to.dsd))",
      "- **Implementation details:**",
      ((.implementation_details // []) | .[] | "  - \(.)"),
      "- **Verification:**",
      "  - Acceptance: `\(.verification_steps.acceptance // "—")`",
      "  - ISC detection: `\(.verification_steps.isc_detection // "—")`",
      "  - DSD conformance: `\(.verification_steps.dsd_conformance // "—")`",
      (if (.human_check_needed.required // false) then "- **Human check reason:** \(.human_check_needed.reason // "—")" else empty end),
      ""
    )
' "$JSON_PATH" > "$MD_PATH" 2>/dev/null || { echo "render_queue.sh: failed to render $MD_PATH" >&2; exit 1; }

exit 0
